services:
  db:
    image: docker.io/postgres:18-alpine
    container_name: community_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_EXTERNAL_PORT}:5432'
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d:ro,Z
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 512m

  redis:
    image: docker.io/redis:7.4-alpine
    container_name: community_redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - '${REDIS_EXTERNAL_PORT}:6379'
    volumes:
      - redis_data_vol:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 256m

volumes:
  postgres_data_vol:
  redis_data_vol:
