spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/community_management_system}
    username: ${SPRING_DATASOURCE_USER:dev_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password}

  docker:
    compose:
      enabled: true
      file: ../compose.yaml
      lifecycle-management: start_and_stop

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

worker:
  retry:
    base-delay: 5s
    max-delay: 300s
    max-retries: 10