spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_and_stop
      skip:
        in-tests: false

  mvc:
    problemdetails:
      enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 1d
  cookie-name: AUTH_TOKEN
  cookie-path: /
  cookie-secure: false
  cookie-same-site: Lax

worker:
  retry:
    base-delay: 5s
    max-delay: 300s
    max-retries: 10
