drop table if exists "event" cascade;

drop table if exists "account" cascade;

create table if not exists event
(
    id bigint generated by default as identity
        constraint events_pkey
            primary key,
    type varchar(100) not null,
    payload jsonb,
    status varchar(20) default 'waiting'::character varying not null
        constraint chk_event_status
            check ((status)::text = ANY (ARRAY[('waiting'::character varying)::text, ('pending'::character varying)::text, ('running'::character varying)::text, ('succeeded'::character varying)::text, ('failed'::character varying)::text, ('dead'::character varying)::text])),
    retry_count integer default 0 not null,
    error_msg text,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    next_run_at timestamp with time zone default CURRENT_TIMESTAMP,
    updated_at timestamp with time zone default CURRENT_TIMESTAMP,
    current_step varchar(50)
);

comment on column event.id is '事件的唯一标识符。';

comment on column event.type is '事件的类型，用于提供给 worker 分配任务。';

comment on column event.payload is '事件所需的参数。';

comment on column event.status is '事件的状态：waiting(等待), running(处理中), succeeded(成功), failed(失败), dead(死亡).';

comment on column event.retry_count is '事件重试次数。';

comment on column event.error_msg is '事件产生错误时的错误消息。';

comment on column event.created_at is '事件创建时的时间戳。';

comment on column event.next_run_at is '事件下一次尝试的时间戳。';

comment on column event.updated_at is '事件更新的时间戳。';

comment on column event.current_step is '当前所在的步骤。';

create index if not exists idx_event_waiting
    on event (next_run_at)
    where ((status)::text = 'waiting'::text);

create table if not exists account
(
    id bigint generated by default as identity
        constraint pk_account
            primary key,
    username varchar(50) not null
        constraint uq_account_username
            unique,
    password_hash varchar(255) not null,
    email varchar(255)
        constraint uq_account_email
            unique,
    phone varchar(20)
        constraint uq_account_phone
            unique,
    profile jsonb,
    status varchar(20) default 'normal'::character varying not null
        constraint chk_account_status
            check ((status)::text = ANY (ARRAY[('normal'::character varying)::text, ('suspended'::character varying)::text, ('archived'::character varying)::text])),
    role varchar(20) default 'user'::character varying not null
        constraint chk_account_role
            check ((role)::text = ANY ((ARRAY['user'::character varying, 'admin'::character varying, 'owner'::character varying])::text[])),
    created_at timestamp with time zone default CURRENT_TIMESTAMP not null,
    updated_at timestamp with time zone default CURRENT_TIMESTAMP not null,
    last_login_at timestamp with time zone,
    last_login_ip inet,
    nickname varchar(50)
);

comment on column account.id is '账户的唯一标识符';

comment on column account.username is '账户的唯一用户名';

comment on column account.password_hash is '加密后的密码';

comment on column account.email is '账户关联的电子邮箱地址';

comment on column account.phone is '账户关联的手机号码';

comment on column account.profile is '账户的个人信息';

comment on column account.status is '账户的状态';

comment on column account.role is '账户所在的用户组';

comment on column account.created_at is '账户创建的时间戳';

comment on column account.updated_at is '账户上次更新的时间';

comment on column account.last_login_at is '账户上次的登录时间';

comment on column account.last_login_ip is '账户上次的登录IP地址';

